name: Exploring K240
baseurl: https://tetracorp.github.io/k240
markdown: redcarpet
pygments: true
destination: ../k240
kramdown:
  input: GFM
  hard_wrap: false
redcarpet:
  extensions: ['tables', 'strikethrough', 'no_intra_emphasis', 'autolink']
permalink: none

